#============================
# QuickFind class Makefile
#
# Author: Brendon Roberto
#
# ===========================


CXX					= g++
INCLUDE_OPT = -iquote .
DOP 				= -a

CXX_FLAGS   = -g -O -Wall -W -Wunused -Wuninitialized -Wshadow

ECHO				= /bin/echo

UNION_H			= union.h
UNION_O			= union.o

#=============================
# Tests
#=============================

TEST_PROG_1 	= test_quickfind_constructors

TEST_PROG_DIR = ./tests

#=============================

msg:
	@echo 'Targets for compiling test programs:'
	@echo '			t1 or ${TEST_PROG_1}'


